/* In-preview academic checklist, separate from everyday operations. */
(() => {
  'use strict';
  function show(app) {
    const rows=[['Đăng nhập & phân quyền','Đăng xuất để thử Admin, Manager, Nhân viên hoặc Customer.'],['Khu vực / vị trí / loại xe / giá','Bãi đỗ và Loại xe & bảng giá: thêm, sửa, ngừng dùng, xóa mục chưa được sử dụng.'],['Xe vào/ra, thời gian và phí','Vận hành → Nhập tay. Không cần đặt trước; thu tiền rồi trả xe.'],['Chỗ trống theo khu','Bãi đỗ → Sơ đồ: trống, có xe, giữ trước, tạm ngừng.'],['Tra cứu lượt gửi','Lịch sử: biển/mã vé, từ ngày–đến ngày, trạng thái; mở chi tiết.'],['Khách quen, phương tiện, vé tháng','Khách & vé: hồ sơ, liên kết xe, cấp vé và gia hạn.'],['Thống kê lưu lượng / doanh thu / cao điểm','Báo cáo: kỳ ngày/tuần, tổng vào/ra, tiền đã thu, khung giờ đông.'],['AI báo cáo / hỏi đáp / nhân sự','Báo cáo → AI: chọn kỳ, sinh kết quả, xem dữ liệu nguồn và lịch sử. Chatbot góc phải trả lời theo quyền.']];
    const body=`<p>Demo tương tác để duyệt đầy đủ các luồng theo đề tài. Tất cả số liệu là mẫu và có thể thay đổi khi bạn thao tác.</p><div class="table-wrap"><table class="data-table"><thead><tr><th>Yêu cầu</th><th>Cách thử</th></tr></thead><tbody>${rows.map(([a,b])=>`<tr><td>${a}</td><td>${b}</td></tr>`).join('')}</tbody></table></div><h3>Minh chứng dùng AI trong SDLC</h3><ol class="guide-list"><li><strong>KT1:</strong> phân tích một xe/một lượt, chỗ có thể nhận, giá lúc vào và vé tháng; mô hình demo gồm khu, vị trí, loại xe, khách, phương tiện, lượt, vé, phiếu thu.</li><li><strong>KT2:</strong> mã nguồn demo và test nhận/trả xe, tính phí, vé tháng, chỗ bị giữ hoặc ngừng phục vụ.</li><li><strong>KT3:</strong> test báo cáo rỗng/sai, quyền xem dữ liệu, ngày/tuần và gợi ý nhân sự. Câu trả lời mô phỏng chỉ diễn giải số liệu đã tính.</li><li><strong>Cuối kỳ:</strong> hướng dẫn chạy, ma trận yêu cầu và kết quả kiểm tra ở README.md và SDLC_EVIDENCE.md đi kèm demo.</li></ol><details><summary>Xem prompt dự kiến cho AI thật</summary><pre class="prompt-preview">System: Bạn là trợ lý phân tích bãi đỗ xe. Không tự tạo số liệu, chỉ nhận xét từ dữ liệu được cung cấp. Phân biệt chỗ hiện tại với thống kê của kỳ. Nếu thiếu dữ liệu, nói rõ giới hạn.\nUser: Dữ liệu lưu lượng ngày/tuần: {{parking_stats}}. Hãy tóm tắt cao điểm và gợi ý bố trí nhân sự; nêu rõ mọi giả định.</pre></details><p class="inline-note">Bản này dùng HTML/JavaScript và dữ liệu trong RAM. AI trả lời theo quy tắc mô phỏng, không gọi model. Backend, CSDL, xác thực và AI thật thuộc bước tích hợp sau khi bạn duyệt giao diện.</p>`;
    app.showModal('Đối chiếu đề tài & hướng dẫn thử',body);
    document.querySelector('.modal')?.classList.add('modal-wide');
  }
  window.DemoGuide={show};
})();
