"""Create the initial production PostgreSQL schema.

Revision ID: 20260828_01
Revises: None
Create Date: 2026-08-28

This is intentionally an explicit, reviewed baseline rather than an
autogenerated approximation of SQLite.  PostgreSQL constraints and triggers
preserve the same cross-request invariants when blue and green containers are
both connected to the managed database.
"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

from core.money import MAX_EXACT_VND


revision: str = "20260828_01"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def _timestamps() -> tuple[sa.Column, sa.Column]:
    return (
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )


def upgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF current_setting('server_encoding') <> 'UTF8' THEN
                RAISE EXCEPTION 'ParkingAI requires PostgreSQL UTF8 encoding';
            END IF;
        END
        $$
        """
    )
    # daterange exclusion is the concurrency-safe backstop for active passes.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        """
        CREATE OR REPLACE FUNCTION unicode_casefold(value text)
        RETURNS text
        LANGUAGE sql
        IMMUTABLE STRICT PARALLEL SAFE
        RETURN lower(normalize(btrim(value), NFC))
        """
    )

    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(50), nullable=False),
        sa.Column("description", sa.String(255), nullable=True),
        *_timestamps(),
    )
    op.create_index("uq_roles_name", "roles", ["name"], unique=True)

    op.create_table(
        "vehicle_types",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(50), nullable=False),
        sa.Column("description", sa.String(255), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        *_timestamps(),
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_vehicle_types_name_normalized "
        "ON vehicle_types (unicode_casefold(name))"
    )

    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("full_name", sa.String(100), nullable=False),
        sa.Column("phone_number", sa.String(20), nullable=False, unique=True),
        sa.Column("email", sa.String(100), nullable=True),
        *_timestamps(),
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_customers_phone_normalized "
        "ON customers (unicode_casefold(phone_number))"
    )

    op.create_table(
        "zones",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(50), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        *_timestamps(),
        sa.CheckConstraint("capacity >= 0", name="ck_zones_capacity_nonnegative"),
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_zones_name_normalized "
        "ON zones (unicode_casefold(name))"
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "role_id",
            sa.Integer(),
            sa.ForeignKey("roles.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("username", sa.String(50), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("full_name", sa.String(100), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        *_timestamps(),
    )

    op.create_table(
        "parking_slots",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "zone_id",
            sa.Integer(),
            sa.ForeignKey("zones.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "vehicle_type_id",
            sa.Integer(),
            sa.ForeignKey("vehicle_types.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("slot_name", sa.String(50), nullable=False),
        sa.Column(
            "is_occupied", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        *_timestamps(),
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_parking_slots_name_normalized "
        "ON parking_slots (unicode_casefold(slot_name))"
    )

    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("license_plate", sa.String(20), nullable=False, unique=True),
        sa.Column(
            "vehicle_type_id",
            sa.Integer(),
            sa.ForeignKey("vehicle_types.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "customer_id",
            sa.Integer(),
            sa.ForeignKey("customers.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        *_timestamps(),
    )

    op.create_table(
        "price_configs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "vehicle_type_id",
            sa.Integer(),
            sa.ForeignKey("vehicle_types.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("ticket_type", sa.String(20), nullable=False),
        sa.Column("price", sa.BigInteger(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        *_timestamps(),
        sa.CheckConstraint(
            "ticket_type IN ('HOURLY', 'DAILY')",
            name="ck_price_configs_ticket_type",
        ),
        sa.CheckConstraint(
            f"price BETWEEN 0 AND {MAX_EXACT_VND}",
            name="ck_price_configs_exact_vnd",
        ),
    )
    op.create_index(
        "uq_price_config_one_active_per_vehicle_type",
        "price_configs",
        ["vehicle_type_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )

    op.create_table(
        "monthly_passes",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "customer_id",
            sa.Integer(),
            sa.ForeignKey("customers.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "vehicle_id",
            sa.Integer(),
            sa.ForeignKey("vehicles.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("pass_code", sa.String(50), nullable=True),
        sa.Column(
            "price", sa.BigInteger(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        *_timestamps(),
        sa.CheckConstraint(
            f"price BETWEEN 0 AND {MAX_EXACT_VND}",
            name="ck_monthly_passes_exact_vnd",
        ),
        sa.CheckConstraint(
            "end_date >= start_date", name="ck_monthly_passes_date_range"
        ),
    )
    op.create_index(
        "ix_monthly_passes_pass_code",
        "monthly_passes",
        ["pass_code"],
        unique=True,
        postgresql_where=sa.text("pass_code IS NOT NULL"),
    )
    op.execute(
        """
        ALTER TABLE monthly_passes
        ADD CONSTRAINT ex_monthly_passes_no_active_overlap
        EXCLUDE USING gist (
            vehicle_id WITH =,
            daterange(start_date, end_date, '[]') WITH &&
        ) WHERE (is_active)
        """
    )

    op.create_table(
        "parking_sessions",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "vehicle_id",
            sa.Integer(),
            sa.ForeignKey("vehicles.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "parking_slot_id",
            sa.Integer(),
            sa.ForeignKey("parking_slots.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column(
            "monthly_pass_id",
            sa.Integer(),
            sa.ForeignKey("monthly_passes.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column("check_in_time", sa.DateTime(), nullable=False),
        sa.Column("check_out_time", sa.DateTime(), nullable=True),
        sa.Column("image_in_url", sa.String(255), nullable=True),
        sa.Column("image_out_url", sa.String(255), nullable=True),
        sa.Column("parking_fee", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column(
            "staff_in_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "staff_out_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        *_timestamps(),
        sa.CheckConstraint(
            "status IN ('active', 'checking_out', 'completed', 'cancelled')",
            name="ck_parking_sessions_status",
        ),
        sa.CheckConstraint(
            f"parking_fee IS NULL OR parking_fee BETWEEN 0 AND {MAX_EXACT_VND}",
            name="ck_parking_sessions_exact_vnd",
        ),
        sa.CheckConstraint(
            "(status = 'completed' AND check_out_time IS NOT NULL "
            "AND parking_fee IS NOT NULL AND staff_out_id IS NOT NULL "
            "AND check_out_time >= check_in_time) OR "
            "(status IN ('active', 'checking_out') AND check_out_time IS NULL "
            "AND parking_fee IS NULL AND staff_out_id IS NULL) OR "
            "status = 'cancelled'",
            name="ck_parking_sessions_state",
        ),
    )
    op.create_index(
        "uq_parking_session_one_active_per_vehicle",
        "parking_sessions",
        ["vehicle_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "uq_parking_session_one_active_per_slot",
        "parking_sessions",
        ["parking_slot_id"],
        unique=True,
        postgresql_where=sa.text(
            "status = 'active' AND parking_slot_id IS NOT NULL"
        ),
    )

    op.create_table(
        "ai_reports",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("report_type", sa.String(50), nullable=False),
        sa.Column("prompt_used", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "generated_by_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(50), nullable=False),
        sa.Column("action", sa.String(30), nullable=False),
        sa.Column("resource", sa.String(80), nullable=False),
        sa.Column("resource_id", sa.String(80), nullable=True),
        sa.Column("method", sa.String(10), nullable=False),
        sa.Column("path", sa.String(255), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column(
            "success", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        sa.Column("ip_address", sa.String(64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    for column in ("user_id", "username", "action", "resource", "success", "created_at"):
        op.create_index(f"ix_audit_logs_{column}", "audit_logs", [column])

    _create_updated_at_trigger()
    _create_vehicle_history_guard()
    _create_monthly_pass_history_guard()
    _create_price_guard()
    _create_zone_slot_guards()
    _create_session_guard()


def _create_updated_at_trigger() -> None:
    op.execute(
        """
        CREATE FUNCTION parkingai_touch_updated_at()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            NEW.updated_at = CURRENT_TIMESTAMP;
            RETURN NEW;
        END;
        $$
        """
    )
    for table in (
        "roles",
        "vehicle_types",
        "customers",
        "zones",
        "users",
        "parking_slots",
        "vehicles",
        "price_configs",
        "monthly_passes",
        "parking_sessions",
    ):
        op.execute(
            f"CREATE TRIGGER trg_{table}_touch_updated_at "
            f"BEFORE UPDATE ON {table} FOR EACH ROW "
            "EXECUTE FUNCTION parkingai_touch_updated_at()"
        )


def _create_vehicle_history_guard() -> None:
    op.execute(
        """
        CREATE FUNCTION parkingai_guard_vehicle_history()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NEW.vehicle_type_id IS DISTINCT FROM OLD.vehicle_type_id
               AND (EXISTS (SELECT 1 FROM parking_sessions WHERE vehicle_id = OLD.id)
                    OR EXISTS (SELECT 1 FROM monthly_passes WHERE vehicle_id = OLD.id)) THEN
                RAISE EXCEPTION 'vehicle type immutable after history';
            END IF;
            IF NEW.license_plate IS DISTINCT FROM OLD.license_plate
               AND EXISTS (SELECT 1 FROM parking_sessions WHERE vehicle_id = OLD.id) THEN
                RAISE EXCEPTION 'license plate immutable after history';
            END IF;
            RETURN NEW;
        END;
        $$;
        CREATE TRIGGER trg_vehicles_history_guard
        BEFORE UPDATE OF vehicle_type_id, license_plate ON vehicles
        FOR EACH ROW EXECUTE FUNCTION parkingai_guard_vehicle_history();
        """
    )


def _create_monthly_pass_history_guard() -> None:
    op.execute(
        """
        CREATE FUNCTION parkingai_guard_monthly_pass_history()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF EXISTS (SELECT 1 FROM parking_sessions WHERE monthly_pass_id = OLD.id)
               AND (NEW.customer_id IS DISTINCT FROM OLD.customer_id
                    OR NEW.vehicle_id IS DISTINCT FROM OLD.vehicle_id
                    OR NEW.pass_code IS DISTINCT FROM OLD.pass_code
                    OR NEW.price IS DISTINCT FROM OLD.price
                    OR NEW.start_date IS DISTINCT FROM OLD.start_date
                    OR NEW.end_date IS DISTINCT FROM OLD.end_date) THEN
                RAISE EXCEPTION 'monthly pass history immutable';
            END IF;
            RETURN NEW;
        END;
        $$;
        CREATE TRIGGER trg_monthly_passes_history_immutable
        BEFORE UPDATE OF customer_id, vehicle_id, pass_code, price,
            start_date, end_date ON monthly_passes
        FOR EACH ROW EXECUTE FUNCTION parkingai_guard_monthly_pass_history();
        """
    )


def _create_price_guard() -> None:
    op.execute(
        """
        CREATE FUNCTION parkingai_guard_price_with_active_sessions()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            protected_type integer := OLD.vehicle_type_id;
        BEGIN
            -- Serialize with session admission for this vehicle type. Without
            -- the shared lock, two READ COMMITTED statements could both pass
            -- their pre-check and commit an active stay without a rate.
            PERFORM 1 FROM vehicle_types
            WHERE id = protected_type FOR UPDATE;
            IF OLD.is_active AND EXISTS (
                SELECT 1 FROM parking_sessions ps
                JOIN vehicles v ON v.id = ps.vehicle_id
                WHERE ps.status IN ('active', 'checking_out')
                  AND v.vehicle_type_id = protected_type
            ) THEN
                IF TG_OP = 'DELETE' OR NEW.vehicle_type_id IS DISTINCT FROM OLD.vehicle_type_id
                   OR NEW.ticket_type IS DISTINCT FROM OLD.ticket_type
                   OR NEW.price IS DISTINCT FROM OLD.price
                   OR NEW.effective_date IS DISTINCT FROM OLD.effective_date
                   OR NEW.is_active IS DISTINCT FROM OLD.is_active THEN
                    RAISE EXCEPTION 'active parking session uses price config';
                END IF;
            END IF;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            RETURN NEW;
        END;
        $$;
        CREATE TRIGGER trg_price_configs_active_session_update_guard
        BEFORE UPDATE ON price_configs FOR EACH ROW
        EXECUTE FUNCTION parkingai_guard_price_with_active_sessions();
        CREATE TRIGGER trg_price_configs_active_session_delete_guard
        BEFORE DELETE ON price_configs FOR EACH ROW
        EXECUTE FUNCTION parkingai_guard_price_with_active_sessions();
        """
    )


def _create_zone_slot_guards() -> None:
    op.execute(
        """
        CREATE FUNCTION parkingai_guard_zone_update()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NEW.capacity < (SELECT count(*) FROM parking_slots WHERE zone_id = OLD.id) THEN
                RAISE EXCEPTION 'zone capacity below slot count';
            END IF;
            IF OLD.is_active AND NOT NEW.is_active AND EXISTS (
                SELECT 1 FROM parking_slots ps
                WHERE ps.zone_id = OLD.id AND (
                    ps.is_occupied OR EXISTS (
                        SELECT 1 FROM parking_sessions s
                        WHERE s.parking_slot_id = ps.id
                          AND s.status IN ('active', 'checking_out')
                    )
                )
            ) THEN
                RAISE EXCEPTION 'zone has active parking';
            END IF;
            RETURN NEW;
        END;
        $$;
        CREATE TRIGGER trg_zones_operational_update_guard
        BEFORE UPDATE OF capacity, is_active ON zones
        FOR EACH ROW EXECUTE FUNCTION parkingai_guard_zone_update();

        CREATE FUNCTION parkingai_guard_slot_write()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            destination_capacity integer;
            destination_count integer;
        BEGIN
            PERFORM 1 FROM zones WHERE id = NEW.zone_id FOR UPDATE;
            SELECT capacity INTO destination_capacity FROM zones WHERE id = NEW.zone_id;

            IF TG_OP = 'INSERT' OR NEW.zone_id IS DISTINCT FROM OLD.zone_id THEN
                SELECT count(*) INTO destination_count
                FROM parking_slots WHERE zone_id = NEW.zone_id;
                IF destination_count >= destination_capacity THEN
                    RAISE EXCEPTION 'zone capacity exceeded';
                END IF;
            END IF;

            IF TG_OP = 'UPDATE' THEN
                IF NEW.zone_id IS DISTINCT FROM OLD.zone_id
                   AND EXISTS (SELECT 1 FROM parking_sessions WHERE parking_slot_id = OLD.id) THEN
                    RAISE EXCEPTION 'slot zone immutable after history';
                END IF;
                IF ((OLD.is_active AND NOT NEW.is_active)
                    OR NEW.zone_id IS DISTINCT FROM OLD.zone_id
                    OR NEW.vehicle_type_id IS DISTINCT FROM OLD.vehicle_type_id)
                   AND (OLD.is_occupied OR EXISTS (
                       SELECT 1 FROM parking_sessions
                       WHERE parking_slot_id = OLD.id
                         AND status IN ('active', 'checking_out')
                   )) THEN
                    RAISE EXCEPTION 'slot has active parking';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$;
        CREATE TRIGGER trg_parking_slots_capacity_and_operation_guard
        BEFORE INSERT OR UPDATE OF zone_id, vehicle_type_id, is_active
        ON parking_slots FOR EACH ROW EXECUTE FUNCTION parkingai_guard_slot_write();
        """
    )


def _create_session_guard() -> None:
    op.execute(
        """
        CREATE FUNCTION parkingai_validate_session()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            session_vehicle_type integer;
            session_zone integer;
        BEGIN
            -- One lock order for every admission path: vehicle -> type ->
            -- slot -> zone. Price updates share the type lock; slot/zone
            -- updates share their row locks. This closes cross-container
            -- check-then-act races under READ COMMITTED.
            SELECT vehicle_type_id INTO session_vehicle_type
            FROM vehicles WHERE id = NEW.vehicle_id FOR UPDATE;
            PERFORM 1 FROM vehicle_types
            WHERE id = session_vehicle_type FOR UPDATE;
            IF NEW.parking_slot_id IS NOT NULL THEN
                SELECT zone_id INTO session_zone FROM parking_slots
                WHERE id = NEW.parking_slot_id FOR UPDATE;
                PERFORM 1 FROM zones WHERE id = session_zone FOR UPDATE;
            END IF;

            IF TG_OP = 'UPDATE' THEN
                IF NEW.vehicle_id IS DISTINCT FROM OLD.vehicle_id
                   OR NEW.parking_slot_id IS DISTINCT FROM OLD.parking_slot_id
                   OR NEW.monthly_pass_id IS DISTINCT FROM OLD.monthly_pass_id
                   OR NEW.check_in_time IS DISTINCT FROM OLD.check_in_time
                   OR NEW.staff_in_id IS DISTINCT FROM OLD.staff_in_id THEN
                    RAISE EXCEPTION 'parking session identity is immutable';
                END IF;

                IF OLD.status = 'completed' AND (
                    NEW.status IS DISTINCT FROM OLD.status
                    OR NEW.check_out_time IS DISTINCT FROM OLD.check_out_time
                    OR NEW.parking_fee IS DISTINCT FROM OLD.parking_fee
                    OR NEW.staff_out_id IS DISTINCT FROM OLD.staff_out_id
                ) THEN
                    RAISE EXCEPTION 'completed parking session is immutable';
                END IF;

                IF NEW.status = 'checking_out' AND OLD.status <> 'active' THEN
                    RAISE EXCEPTION 'parking session status invalid';
                END IF;
                IF OLD.status = 'checking_out' AND NEW.status <> 'completed' THEN
                    RAISE EXCEPTION 'parking session status invalid';
                END IF;
            ELSIF NEW.status = 'checking_out' THEN
                RAISE EXCEPTION 'parking session status invalid';
            END IF;

            -- Entitlement is a check-in snapshot. Deactivating a pass later
            -- must not prevent the already-admitted session from completing.
            IF TG_OP = 'INSERT' AND NEW.monthly_pass_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM monthly_passes mp
                WHERE mp.id = NEW.monthly_pass_id
                  AND mp.vehicle_id = NEW.vehicle_id
                  AND mp.is_active
                  AND mp.start_date <= NEW.check_in_time::date
                  AND mp.end_date >= NEW.check_in_time::date
            ) THEN
                RAISE EXCEPTION 'monthly pass is not eligible at check-in';
            END IF;

            IF NEW.status = 'active' AND NOT EXISTS (
                SELECT 1 FROM price_configs pc
                WHERE pc.vehicle_type_id = session_vehicle_type AND pc.is_active
                  AND pc.effective_date <= NEW.check_in_time::date
            ) THEN
                RAISE EXCEPTION 'active parking session requires effective price config';
            END IF;

            IF NEW.status = 'active' AND NEW.parking_slot_id IS NOT NULL
               AND NOT EXISTS (
                SELECT 1 FROM parking_slots ps
                JOIN zones z ON z.id = ps.zone_id
                JOIN vehicles v ON v.id = NEW.vehicle_id
                WHERE ps.id = NEW.parking_slot_id
                  AND ps.vehicle_type_id = v.vehicle_type_id
                  AND ps.is_active AND z.is_active
            ) THEN
                RAISE EXCEPTION 'parking slot is not eligible for active session';
            END IF;
            RETURN NEW;
        END;
        $$;
        CREATE TRIGGER trg_parking_sessions_validate
        BEFORE INSERT OR UPDATE ON parking_sessions
        FOR EACH ROW EXECUTE FUNCTION parkingai_validate_session();
        """
    )


def downgrade() -> None:
    # Production rollbacks use application roll-forward/blue-green switching.
    # This destructive baseline downgrade exists for disposable environments.
    for table in (
        "audit_logs",
        "ai_reports",
        "parking_sessions",
        "monthly_passes",
        "price_configs",
        "vehicles",
        "parking_slots",
        "users",
        "zones",
        "customers",
        "vehicle_types",
        "roles",
    ):
        op.drop_table(table)
    for function_name in (
        "parkingai_validate_session",
        "parkingai_guard_slot_write",
        "parkingai_guard_zone_update",
        "parkingai_guard_price_with_active_sessions",
        "parkingai_guard_monthly_pass_history",
        "parkingai_guard_vehicle_history",
        "parkingai_touch_updated_at",
    ):
        op.execute(f"DROP FUNCTION IF EXISTS {function_name}() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS unicode_casefold(text) CASCADE")
